# Generated by Django 2.0.6 on 2018-06-14 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Encargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catidade', models.IntegerField()),
            ],
            options={
                'ordering': ('encargo',),
            },
        ),
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('localizacion', models.CharField(choices=[('1', 'Area 1'), ('2', 'Area 2')], max_length=2)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='detalle_encargo',
            name='encargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='encargos.Encargo'),
        ),
        migrations.AddField(
            model_name='detalle_encargo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargos.Producto'),
        ),
    ]
