# Generated by Django 2.0.6 on 2018-06-14 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encargos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Encargo', to=settings.AUTH_USER_MODEL),
        ),
    ]
