# Generated by Django 2.0.6 on 2018-06-15 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encargos', '0002_auto_20180614_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos', to=settings.AUTH_USER_MODEL),
        ),
    ]
