# Generated by Django 2.0.6 on 2018-06-16 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encargos', '0003_auto_20180615_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_encargo',
            options={},
        ),
        migrations.RenameField(
            model_name='detalle_encargo',
            old_name='catidade',
            new_name='cantidade',
        ),
        migrations.AlterField(
            model_name='detalle_encargo',
            name='encargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encargos.Encargo'),
        ),
        migrations.AlterField(
            model_name='detalle_encargo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='encargos.Producto'),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='localizacion',
            field=models.CharField(choices=[('1', 'Area 1'), ('2', 'Area 2')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
